name: Publish Package to NPM
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write 

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write
      packages: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 

      - name: ðŸ”Ž DEBUG :- Show Git Info
        run: |
          echo "Current Commit: $(git rev-parse HEAD)"
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
          
      - name: Set up Node.js 
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          registry-url: 'https://registry.npmjs.org'
          
      - name: ðŸ”Ž DEBUG :- Check npm configuration
        run: npm config ls -l | grep registry

      - name: Install dependencies (CI)
        run: npm ci 
        
      - name: Run Build
        run: npm run build
        
      - name: Run Tests (if script exists)
        run: npm test --if-present

      - name: Bump version, determine publish tag, and set output
        id: versioning_and_tagging
        run: |
          # 1. Read the new, bumped version
          VERSION=$(jq -r .version package.json)
          PUBLISH_TAG=""

          echo "Detected new package version: $VERSION"

          # 2. Determine tag logic
          if [[ "$VERSION" == *"-rc"* ]]; then
            PUBLISH_TAG="beta"
            echo "Match '-rc' prerelease: Setting tag to 'beta'"
          elif [[ "$VERSION" != *"-"* ]]; then
            PUBLISH_TAG="latest"
            echo "No hyphen found: Setting tag to 'latest' (stable version)"
          else
            PUBLISH_TAG="pre"
            echo "Match other prerelease (contains '-'): Setting tag to 'pre'"
          fi
          
          echo "Calculated NPM Tag: $PUBLISH_TAG"
          
          # Set outputs for use in later steps
          echo "PUBLISH_TAG=$PUBLISH_TAG" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=$VERSION" >> $GITHUB_OUTPUT 

      - name: ðŸ”Ž DEBUG :- Check Tag Output
        run: echo "Tag determined by previous step :- ${{ steps.versioning_and_tagging.outputs.PUBLISH_TAG }}"
      
      - name: Publish Package NPM Registry ðŸš€
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          tag: ${{ steps.versioning_and_tagging.outputs.PUBLISH_TAG }}
          provenance: true
          registry: 'https://registry.npmjs.org'

      - name: Publish Package GITHUB Registry ðŸš€
        uses: JS-DevTools/npm-publish@v4.1.1
        with:
          tag: ${{ steps.versioning_and_tagging.outputs.PUBLISH_TAG }}
          provenance: true
          registry: "https://npm.pkg.github.com"
