name: Publish Package to NPM
on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js for Trusted Publish (OIDC)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies (CI)
        run: npm ci
        
      - name: Run Build (if script exists)
        run: npm run build --if-present
        
      - name: Run Tests (if script exists)
        run: npm test --if-present

      - name: Determine Publish Tag
        id: determine_tag
        run: |
          VERSION=$(jq -r .version package.json)
          PUBLISH_TAG=""

          echo "Detected package version: $VERSION"

          if [[ "$VERSION" == *"-rc"* ]]; then
            PUBLISH_TAG="beta"
          elif [[ "$VERSION" != *"-"* ]]; then
            PUBLISH_TAG="latest"
          else
            PUBLISH_TAG="pre"
          fi
          
          echo "Calculated NPM Tag: $PUBLISH_TAG"
          echo "PUBLISH_TAG=$PUBLISH_TAG" >> $GITHUB_OUTPUT

      - name: Publish Package
        run: npm publish --access public --tag ${{ steps.determine_tag.outputs.PUBLISH_TAG }} --provenance
        env:
          PUBLISH_TAG: ${{ steps.determine_tag.outputs.PUBLISH_TAG }}